// ---------------------------------------------------------------------------
// Report explainer — deterministic, template-driven natural-language
// generation over the report's OWN data (patient, risk assessment, signal
// features). Deliberately NOT a RAG pipeline or an external LLM call:
// - No vector store, no document retrieval, no embeddings.
// - No network request — everything it says is derived from the structured
//   fields already loaded for this report, so its answers are traceable
//   back to a specific field every time ("explainable" in the literal sense).
// - Intent matching is simple keyword rules, good enough for the bounded set
//   of things a clinician actually asks about a report.
//
// If a real LLM-backed explainer is wanted later, swap this module out
// behind chatService (mirrors every other service's mock/real split) and
// point it at a FastAPI endpoint like POST /api/reports/{id}/chat — nothing
// in the UI needs to change.
// ---------------------------------------------------------------------------
import type { ReportContext } from '@/types'
import { RISK_LABELS } from '@/constants'

function qualityDescriptor(score: number): string {
  if (score >= 85) return 'excellent'
  if (score >= 70) return 'good'
  if (score >= 50) return 'fair'
  return 'poor'
}

export function generateSummary(ctx: ReportContext): string {
  const { report, patientName, risk, features } = ctx
  const durationMin = Math.round(report.monitoringDurationSeconds / 60)
  const quality = qualityDescriptor(report.signalQualityScore)

  return [
    `This report covers a ${durationMin}-minute EHG monitoring session for ${patientName}, recorded on ${new Date(report.createdAt).toLocaleDateString()}.`,
    `Signal quality during the session was ${quality} (${report.signalQualityScore}/100), with an SNR of ${features.snrDb} dB and a dominant contraction frequency of ${features.dominantFrequencyHz} Hz.`,
    `The AI-assisted risk assessment (${risk.modelName} v${risk.modelVersion}) returned "${RISK_LABELS[risk.riskCategory]}" — ${risk.label.toLowerCase()} — at ${(risk.probability * 100).toFixed(0)}% probability.`,
    `The strongest contributing feature was ${risk.contributingFeatures[0]?.name.toLowerCase()} (${risk.contributingFeatures[0]?.value}).`,
    `This is a research/decision-support output, not a diagnosis — it should be reviewed alongside clinical judgment.`,
  ].join(' ')
}

interface Rule {
  test: (q: string) => boolean
  answer: (ctx: ReportContext) => string
}

const RULES: Rule[] = [
  {
    test: (q) => /summar|overview|tl;?dr/.test(q),
    answer: (ctx) => generateSummary(ctx),
  },
  {
    test: (q) => /risk|probability|flag|likelihood/.test(q),
    answer: ({ risk }) =>
      `The model classified this session as "${RISK_LABELS[risk.riskCategory]}" (${risk.label}), with ${(risk.probability * 100).toFixed(0)}% probability, using ${risk.modelName} v${risk.modelVersion}. This reflects a statistical pattern in the extracted signal features, not a clinical diagnosis.`,
  },
  {
    test: (q) => /why|contribut|feature|driver/.test(q),
    answer: ({ risk }) =>
      `The top contributing features were: ${risk.contributingFeatures
        .map((f) => `${f.name} (${f.value}, weight ${(f.weight * 100).toFixed(0)}%)`)
        .join('; ')}. Weights reflect the model's relative reliance on each feature for this session, not a causal explanation.`,
  },
  {
    test: (q) => /quality|snr|noise|clean/.test(q),
    answer: ({ report, features }) =>
      `Signal quality was ${report.signalQualityScore}/100 (${qualityDescriptor(report.signalQualityScore)}), with an SNR of ${features.snrDb} dB. ${
        report.signalQualityScore < 70
          ? 'Lower quality can reduce confidence in the extracted features — consider reviewing electrode contact for this session.'
          : 'This is within a reliable range for feature extraction.'
      }`,
  },
  {
    test: (q) => /duration|long|minutes|time/.test(q),
    answer: ({ report }) => `The monitoring session lasted ${Math.round(report.monitoringDurationSeconds / 60)} minutes.`,
  },
  {
    test: (q) => /model|version|algorithm/.test(q),
    answer: ({ risk }) =>
      `This assessment was generated by ${risk.modelName}, version ${risk.modelVersion} — a bidirectional GRU/LSTM model trained on sequential EHG features. PREG AI's frontend is model-agnostic and simply renders whatever the backend returns, so this may change as the ML team evaluates other architectures.`,
  },
  {
    test: (q) => /diagnos|replace|doctor|clinical/.test(q),
    answer: () =>
      `No — PREG AI provides AI-assisted risk assessment for research and decision support. It does not replace professional medical diagnosis or clinical judgment.`,
  },
]

const FALLBACK =
  "I can answer questions about this specific report — try asking about the risk assessment, what drove it, signal quality, session duration, or the model used. I'm a lightweight rule-based assistant scoped to this report's data, not a general-purpose chatbot."

export function answerQuestion(question: string, ctx: ReportContext): string {
  const q = question.toLowerCase()
  const rule = RULES.find((r) => r.test(q))
  return rule ? rule.answer(ctx) : FALLBACK
}

export const SUGGESTED_QUESTIONS = [
  'Summarize this report',
  'Why was this risk level assigned?',
  'How was signal quality?',
  'Does this replace a doctor?',
]
